# Generated by Django 3.0.8 on 2020-07-11 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usersprofile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('skills', models.TextField(default='', max_length=200)),
                ('interests', models.TextField(default='', max_length=200)),
                ('aboutme', models.TextField(default='', max_length=300)),
                ('fblink', models.URLField(default='facebook.com', max_length=128)),
                ('gitlink', models.URLField(default='github.com', max_length=128)),
                ('avatar', models.ImageField(default='avatar.jpg', upload_to='profile_pictures')),
            ],
        ),
    ]
