# Generated by Django 3.0.8 on 2020-07-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20200711_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='interests',
            field=models.TextField(default='', max_length=200, null=True),
        ),
    ]
