# Generated by Django 3.0.8 on 2020-07-18 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_register', '0003_auto_20200714_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='contents',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectname',
            field=models.CharField(max_length=200),
        ),
    ]
