# Generated by Django 3.0.3 on 2020-09-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_auto_20200718_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(max_length=200)),
                ('LastName', models.TextField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Message', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
