# Generated by Django 3.1.1 on 2021-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_auto_20200718_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='cluster',
            field=models.IntegerField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='skills',
            field=models.TextField(default='', max_length=200),
        ),
    ]
