# Generated by Django 3.1.1 on 2021-02-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_auto_20210220_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='cluster',
            field=models.IntegerField(default=None, max_length=5, null=True),
        ),
    ]
