# Generated by Django 3.1.1 on 2021-02-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0006_auto_20210220_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='cluster',
            field=models.IntegerField(null=True),
        ),
    ]
