# Generated by Django 3.1.1 on 2021-02-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_contactform'),
        ('login_register', '0007_auto_20210220_1809'),
    ]

    operations = [
    ]
