# Generated by Django 3.1.1 on 2021-02-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_merge_20210220_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='cluster',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
